### ISSUE TITLE
Momentary switch need

### ISSUE THREAD

**Issue by sangkooki** [Zzm317/homebridge-mi-ir-remote#4]
Thank you for your efforts.

It needs momentary button/switch.

I'm going to use it for TV channel up/down, volume up/down.

**Comment by Zzm317** [comment]
I will add this later.

**Comment by Zzm317** [comment]
Added

**Comment by sangkooki** [comment]
Wow

It's great. It's perfect working.

Thank you.

And I have another favor.

I have a blueair 'air-purifier'. I want to use it with mi remote.

I'll like to see 'air purifier' icon on the homekit. Is it possible?

**Comment by Zzm317** [comment]
I think it's unpossible...
irremote can't know the current status of your ir air-purifier
so I don't know how to define the fan speed option...

**Comment by sangkooki** [comment]
I got it.

Thank you for your help.

**Comment by s-triant** [comment]
Could you change the momentary switch type to button or create a new type of control that imitates a button?

The momentary switch is by default in OFF state. When you press it, it is ON until you unpress it when it returns to the OFF state. Depending on the device you would like to control, the state may be confusing.

I would like to control my TV. So, since the remote doesn't know the state of the TV, it is better to control it with a button, which doesn't have states. When you press it, the IR will send the command to either switch the TV ON if it is OFF and vise versa. This way it will function exactly as a TV remote control button.
